# config/routes.yaml

hello_world:
    path: /hello
    controller: App\Controller\HelloWorldController::helloWorld
    methods: GET


print_text:
    path: /print/{text}
    controller: App\Controller\PrintController::printText
    methods: GET